{
 "title": "OpenTelemetry Collector",
 "description": "Provides information about the status of the OpenTelemetry Collector",
 "tags": [ "opentelemetry" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "receiver", "label": "receiver", "query": { "query": "label_values(otelsvc_receiver)" } },
   { "name": "exporter", "label": "exporter", "query": { "query": "label_values(otelsvc_exporter)" } },
   { "name": "processor", "label": "processor", "query": { "query": "label_values(processor)" } },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(cluster)" } }
  ]
 },
 "panels": [
  { "title": "Resource Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Throttled",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{cluster=\"$cluster\", namespace=\"opentelemetry\", container=\"otc-container\" }[5m])) by (container, pod, namespace)\n  /\nsum(increase(container_cpu_cfs_periods_total{cluster=\"$cluster\", namespace=\"opentelemetry\", container=\"otc-container\"}[5m])) by (container, pod, namespace) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Throttled",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{cluster=\"$cluster\", namespace=\"opentelemetry\", container=\"otc-container\" }[5m])) by (container, pod, namespace)\n  /\nsum(increase(container_cpu_cfs_periods_total{cluster=\"$cluster\", namespace=\"opentelemetry\", container=\"otc-container\"}[5m])) by (container, pod, namespace) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Utilization x CPU Requested",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"opentelemetry\", container=\"otc-container\" }) by (pod) \n/ sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"opentelemetry\", container=\"otc-container\"}) by (pod) ) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Utilization x CPU Requested",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "targets": [
    {
     "expr": "(sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"opentelemetry\", container=\"otc-container\" }) by (pod) \n/ sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"opentelemetry\", container=\"otc-container\"}) by (pod) ) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Utilization x Memory Requested",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"opentelemetry\", container=\"otc-container\", image!=\"\"}) by (pod) \n/ sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"opentelemetry\", container=\"otc-container\"}) by (pod)) * 100 ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Utilization x Memory Requested",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 11 },
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"opentelemetry\", container=\"otc-container\", image!=\"\"}) by (pod) \n/ sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"opentelemetry\", container=\"otc-container\"}) by (pod)) * 100 ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Receivers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 12, "x": 0, "y": 17 }, "options": { "content": "## Rate of Spans received " } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 17 },
   "options": {
    "content": "## Rate of Metrics received by collector"
   }
  },
  {
   "title": "Spans Accepted vs Refused /Second",
   "type": "timeseries",
   "description": "Rate of spans successfully accepted vs refused per second",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_spans{receiver=~\"$receiver\",cluster=~\"$cluster\"}[1m])) by (env)",
     "legendFormat": "{{receiver}} spans accepted / sec"
    },
    {
     "expr": "sum(rate(otelcol_receiver_refused_spans{receiver=~\"$receiver\",cluster=~\"$cluster\"}[1m])) by (env)",
     "legendFormat": "{{ receiver }} spans refused /sec"
    }
   ]
  },
  {
   "title": "Metrics Accepted vs Refused Received/Second",
   "type": "timeseries",
   "description": "Rate of metrics successfully accepted vs refused per second",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_receiver_accepted_metric_points{receiver=~\"$receiver\",cluster=~\"$cluster\"}[1m])) by (receiver)",
     "legendFormat": "{{receiver}} accepted /sec"
    },
    {
     "expr": "sum(rate(otelcol_receiver_refused_metric_points{receiver=~\"$receiver\",cluster=~\"$cluster\"}[1m])) by (receiver)",
     "legendFormat": "{{ receiver }} refused / sec"
    }
   ]
  },
  {
   "title": "Exporters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 12, "x": 0, "y": 29 }, "options": { "content": "## Rate of Spans sent to APM" } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 29 },
   "options": {
    "content": "## Rate of Metrics sent to Prometheus"
   }
  },
  {
   "title": "Spans Exported vs Failed / Second",
   "type": "timeseries",
   "description": "Rate of spans successfully exported vs Failed per second",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_spans{exporter=~\"$exporter\", exporter!=\"logging\", cluster=~\"$cluster\"}[1m])) by (env,exporter)",
     "legendFormat": "spans sent / sec - {{ exporter }} "
    },
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_spans{exporter=~\"$exporter\", exporter!=\"logging\" ,cluster=~\"$cluster\"}[1m])) by (exporter,env)",
     "legendFormat": "spans failed /sec -> {{ exporter }} "
    }
   ]
  },
  {
   "title": "Metrics Exported vs failed /Second",
   "type": "timeseries",
   "description": "Rate of timeseries successfully exported per second",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(otelcol_exporter_sent_metric_points{exporter=~\"$exporter\", exporter!=\"logging\" ,cluster=~\"$cluster\"}[1m])) by (exporter)",
     "legendFormat": "{{exporter}} sent /sec"
    },
    {
     "expr": "sum(rate(otelcol_exporter_send_failed_metric_points{exporter=~\"$exporter\", exporter!=\"logging\", cluster=~\"$cluster\"}[1m])) by (exporter)",
     "legendFormat": "{{ exporter }} failed / sec"
    }
   ]
  },
  {
   "title": "Processors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Queued Retry Max Queue Length",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(otelcol_processor_queued_retry_queue_length{cluster=~\"$cluster\"})",
       "legendFormat": "Queue Length"
      }
     ]
    },
    {
     "title": "Queued Retry Processor In-queue Latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(otelcol_processor_queued_retry_queue_latency_sum/ otelcol_processor_queued_retry_queue_latency_count{cluster=~\"$cluster\"})",
       "legendFormat": "ms"
      }
     ]
    },
    {
     "title": "Queued Retry Processor Send Latency (ms)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(otelcol_processor_queued_retry_send_latency_sum/ otelcol_processor_queued_retry_send_latency_count{cluster=~\"$cluster\"})",
       "legendFormat": "ms"
      }
     ]
    },
    {
     "title": "Processor Spans Received, Dropped, Accepted, Refused/Second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(otelcol_processor_spans_received{processor=~\"$processor\",cluster=~\"$cluster\"}[1m])) by (processor)",
       "legendFormat": "{{processor}} | received"
      },
      {
       "expr": "sum(rate(otelcol_processor_spans_dropped{processor=~\"$processor\",cluster=~\"$cluster\"}[1m])) by (processor)",
       "legendFormat": "{{processor}} | dropped"
      },
      {
       "expr": "sum(rate(otelcol_processor_accepted_spans{processor=~\"$processor\"}[1m])) by (processor)",
       "legendFormat": "{{processor}} | accepted"
      },
      {
       "expr": "sum(rate(otelcol_processor_refused_spans{processor=~\"$processor\"}[1m])) by (processor)",
       "legendFormat": "{{processor}} | refused"
      }
     ]
    },
    {
     "title": "QueuedRetry Successful vs Failed Sent/Second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(otelcol_processor_queued_retry_success_send{processor=~\"$processor\",cluster=~\"$cluster\"}[1m])) by (processor)",
       "legendFormat": "{{processor}}"
      },
      {
       "expr": "sum(rate(otelcol_processor_queued_retry_fail_send{processor=~\"$processor\",cluster=~\"$cluster\"}[1m])) by (processor)",
       "legendFormat": "{{processor}}"
      }
     ]
    },
    {
     "title": "Spans per Batch (avg from rates)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(otelcol_processor_spans_received{processor=~\"$processor\",cluster=~\"$cluster\"}[1m]) / rate(otelcol_processor_batches_received{processor=~\"$processor\"}[1m])) by (processor)",
       "legendFormat": "{{processor}}"
      }
     ]
    },
    {
     "title": "Batches Received vs Dropped /Second",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(otelcol_processor_batches_received{processor=~\"$processor\",cluster=~\"$cluster\"}[1m])) by (processor)",
       "legendFormat": "{{processor}} | received"
      },
      {
       "expr": "sum(rate(otelcol_processor_trace_batches_dropped{processor=~\"$processor\",cluster=~\"$cluster\"}[1m])) by (processor)",
       "legendFormat": "{{processor}} | trace dropped"
      }
     ]
    },
    {
     "title": "Successful Batches Sent Cumulative",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(otelcol_processor_queued_retry_success_send{processor=~\"$processor\",cluster=~\"$cluster\"}) by (processor)",
       "legendFormat": "{{processor}}"
      }
     ]
    },
    {
     "title": "Enqueued Spans Cumulative",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(otelcol_processor_spans_received{exporter=~\"$exporter\",cluster=~\"$cluster\"}) by (exporter)",
       "legendFormat": "{{exporter}}"
      }
     ]
    }
   ]
  }
 ]
}